name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libsdl2-dev
      run: sudo apt install libsdl2-dev
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy
    - name: Test
      run: cargo test --all --all-features
